name: Deploy Cloud Functions
on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Build Cloud Functions
        run: npm --prefix ./be ci
      - name: install firebase-tools
        run: npm i firebase-tools -g
      # - name: Create SA key
      #   run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TAXX_CE7CF }}' >> $HOME/gcloud.json
      - name: Deploy Cloud Functions
        run: export GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.FIREBASE_SERVICE_ACCOUNT_TAXX_CE7CF }} && firebase deploy --only functions
