name: Deploy Cloud Functions
on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    paths:
      - firestore.json
      - firestore.indexes.json

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm i
      - name: install firebase-tools
        run: npm i firebase-tools -g
      - name: Test rules
        run: npm run test
