name: Deploy dev to Firebase Hosting on merge to dev
on:
  push:
    branches:
      - dev
    paths:
      - fe/**
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: dev
    env:
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
      REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
      REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
      REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
      REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
      REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
      REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
    steps:
      - name: Cache npm dependencies
        uses: actions/cache@v2.1.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/fe/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/fe/package-lock.json') }}
      - uses: actions/checkout@v2
      - run: npm --prefix ./fe install
      - run: npm --prefix ./fe run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TAXX_CE7CF }}'
          channelId: live
          projectId: taxx-ce7cf
