name: Test RULES on pull request
on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    paths:
      - 'tests/**'
      - 'firestore.rules'
      - 'storage.rules'
      - 'jest.config.json'
      - 'jest.rules.config.json'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Cache npm dependencies
        uses: actions/cache@v2.1.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-key: |
            ${{ runner.os }}-npm
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm i
      - name: install firebase-tools
        run: npm i firebase-tools -D
      - name: Test Rules
        run: npm run test
